### ISSUE TITLE
[Feat] Update decision dispatcher sorting

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#1077]
## Context

1. P or B decision
2. Appeal court decision from Jurinet
3. Appeal decisions with a pourvoi

**Comment by BenoitSerrano** [comment]
C'est déjà la cas non ? En high on a les décisions P et B, en medium on a toutes les décisions jurinet (Cour de cass + CA) + les décisions de CA avec un pourvoi

**Comment by elRomano** [comment]
Je ne peux pas vérifier n'ayant pas l'info mais je te laisse fermer le ticket alors
