### ISSUE TITLE
[Feat] Security improvement for password

### ISSUE THREAD

**Issue by BenoitSerrano** [Cour-de-cassation/label#1156]
## Context
The password must follow PSSI constraints

## Spec
Les caractéristiques obligatoires du mot de passe imposées par la politique ministérielle de défense et de sécurité (PMDS) sont rappelées ci-dessous :

    la durée maximale entre deux renouvellements ne peut être supérieure à 6 mois ;
    un mot de passe doit avoir une longueur minimum de 8 caractères ;
    il doit comporter au minimum 2 minuscules, 2 majuscules, 2 chiffres et 2 caractères spéciaux, ces 8 caractères étant dans le désordre ;
    lors de la création d’un mot de passe, un outil doit vérifier le respect des règles et la qualité du mot de passe ;
    lors d’un renouvellement obligatoire, le nouveau mot de passe doit être différent du précédent ;
    aucun mot de passe, ni secret (clef de chiffrement, clef privée d’authentification ou de signature) ne doit résider ou transiter en clair au sein du système d’information.

**Comment by fondation451** [comment]
Everything is done except for the password change every 6 months.

I have created a specific issue for that https://github.com/Cour-de-cassation/label/issues/1165.

I close here.
