### ISSUE TITLE
Client Error : Client not launching

### ISSUE THREAD

**Issue by AhmedOsman00py** [Cour-de-cassation/label#1671]
Hello, 

I'm trying to get Label in my Macbook pro M1 but I get an error with the client when I run the following command:
`yarn startLocalClientDev` after running this command `yarn startLocalDevDocker`.

### Here is the error when I run `yarn startLocalClientDev` :
<img width="734" alt="startLocalClientDoc_error" src="https://user-images.githubusercontent.com/78887980/192572671-7142c033-9e00-4615-81ba-1ceb011b0611.png">

**Comment by DavidLibeau** [comment]
Hello, I see that you are on Node v18 and on my side I'm still on v16.13.1 but I don't know if there is an impact. I will try to investigate.

**Comment by AhmedOsman00py** [comment]
It worked with Node version 16.13.1, thanks a lot.
