### ISSUE TITLE
"Annotation guide" button

### ISSUE THREAD

**Issue by DaFrenchFrog** [Cour-de-cassation/label#176]
## Context
This feature helps the user to know what to annotate and how.
## Spec
This button is shown in the left side above entities list. 

On click this open a pdf in a blank page.

Link to the guide : https://docs.google.com/document/d/1D-lY_KM3Xu3r69vaF3XdFO7K8rbmMeWNzK5Z2aHl6qQ/edit#

**Comment by elRomano** [comment]
@BenoitSerrano @fondation451 This ticket is ready to be done now.

**Comment by elRomano** [comment]
@BenoitSerrano On pourrait peut-être faire ça si il y a du temps ? :)
