### ISSUE TITLE
Tooltip showing basic info on entity rollover

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#177]
## Context
When hovering on an entity we need to show more context about this one.
## Spec
A tooltip shows how many entities are related, the type of entity, and what replaces this entity (anonymised version of in normal view mode and vice versa).
On click on this tooltip it shows the action tooltip.

**Comment by elRomano** [comment]
Content :
- entity category (with color and icon)
- Occurency amount
- replaced term -> anonymous view : "terme intègre : XXX" / normal view : "pseudonymisation : XXX"

**Comment by elRomano** [comment]
![image](https://user-images.githubusercontent.com/25462034/96855495-17dff780-145d-11eb-80d2-b34a17e4e1c5.png)

**Comment by fondation451** [comment]
DOne
