### ISSUE TITLE
[creating an annotation] detect same words in decision

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#237]
## Context
When creating an annotation a word and checking other same words, we need to check word boundaries.
Ex. If cadastral "202" is annotated, the same characters of "year 2020" must not be included in the annotation.
## Spec
add word boundaries management to avoid detection of parts of another word

**Comment by mauryaland** [comment]
For information, here is the list of non word boundary characters we use in the postprocessing:
{'0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 'È',
 'É',
 'Ê',
 'Î',
 'Ï',
 'Ô',
 'Ö',
 'Ù',
 'Ú',
 'Û',
 'Ü',
 'è',
 'é',
 'ê',
 'î',
 'ï',
 'ô',
 'ö',
 'ù',
 'û',
 '-'}

**Comment by elRomano** [comment]
@BenoitSerrano : the icon name is "extension"
![image](https://user-images.githubusercontent.com/25462034/97963179-ec430280-1db6-11eb-8612-7c42515f7b22.png)
