### ISSUE TITLE
Main font update

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#243]
## Context
Luciole is a font specifically made for disabled readers. We can consider switching it from Montserrat...

**Comment by BenoitSerrano** [comment]
![Capture d’écran de 2020-11-02 16-24-03](https://user-images.githubusercontent.com/28384444/97885616-e4884d00-1d27-11eb-8057-09c95a5f8cde.png)

**Comment by BenoitSerrano** [comment]
Branche change-montserrat-to-luciole
