### ISSUE TITLE
[problem report] dropdown design

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#264]
## Context
![image](https://user-images.githubusercontent.com/25462034/97851708-fe10a100-1cf5-11eb-8a48-b5a9c8bafe46.png)
There is an overlapping of elements.
## Spec
![image](https://user-images.githubusercontent.com/25462034/97853377-53e64880-1cf8-11eb-828a-39a712597748.png)

**Comment by elRomano** [comment]
The option in the spec is ok.

**Comment by fondation451** [comment]
Done
