### ISSUE TITLE
[Decision content] tooltip menu styling

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#269]
## Context
Check the figma file to get the info
![image](https://user-images.githubusercontent.com/25462034/97858317-454f5f80-1cff-11eb-96f0-4ffd77474b75.png)

## Spec
![image](https://user-images.githubusercontent.com/25462034/97858385-5e581080-1cff-11eb-8414-0c3dd7d2a7cf.png)

**Comment by fondation451** [comment]
Done
