### ISSUE TITLE
[category list] design link of two entities

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#272]
## Context
There is two lines for one button.

**Comment by elRomano** [comment]
![image](https://user-images.githubusercontent.com/25462034/97972497-e3f1c400-1dc4-11eb-86ed-b5ba11fd51d5.png)

**Comment by fondation451** [comment]
A first version is done. I close the issue. If necessary, we can reopen it if we want to implement a more complex interaction.
