### ISSUE TITLE
Add a "copy decision" button

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#291]
## Context
For certain decision the user needs to put the decision online. As long as there no way to perform this operation automatically the user needs to manually copy and paste the decision to the cour de cassation website. A button that copy the content to the clipboard could be very useful, even for the MVP.
## Spec
To be designed
![image](https://user-images.githubusercontent.com/25462034/98373034-f24b1480-203e-11eb-834e-5d38f3dfa114.png)

**Comment by fondation451** [comment]
Done
