### ISSUE TITLE
Tooltip menu redesign

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#297]
## Spec
![image](https://user-images.githubusercontent.com/25462034/98152454-0ae9ec00-1ed2-11eb-8527-9e05e5b24b50.png)

**Comment by elRomano** [comment]
@BenoitSerrano @fondation451 This sounds good to me. Note that is a new dropshadow (available in the styleguide) and we will have different drop shadows between light and dark mode

**Comment by fondation451** [comment]
Done
