### ISSUE TITLE
Repair selection behavior on Firefox

### ISSUE THREAD

**Issue by BenoitSerrano** [Cour-de-cassation/label#327]
## Context
On Firefox, when you select text, the selection is automatically unselected

**Comment by elRomano** [comment]
Mind the spacing and small font size for the "occurences identiques".
If we could display the selected text in the tooltip right above the "real" selection it would be perfect. :)

![image](https://user-images.githubusercontent.com/25462034/98947262-42215400-24f5-11eb-8b59-4aefc9b9f77c.png)
![image](https://user-images.githubusercontent.com/25462034/98948075-469a3c80-24f6-11eb-85eb-32e1aa5310bc.png)

**Comment by fondation451** [comment]
Done
