### ISSUE TITLE
hovering color management

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#332]
## Context
We use the Material design color palettes : https://material.io/resources/color/#!/?view.left=0&view.right=0

## Dark mode
background : same color of the button in its 100 alternative
text color + icons : black

## Light mode
background : same color of the button in its 800 alternative
text color + icons : white

**Comment by fondation451** [comment]
@elRomano 
Et pour le `primary` (Jaune) ? Et pour le `secondary` (orange) ? On met la même chose ?

**Comment by fondation451** [comment]
@elRomano 
Tu peux préciser les codes couleurs dans le ticket ? Je ne comprends pas, en "dark mode", les textes et les icones sont noirs ? Et en "light mode", les textes et les icones sont blancs ?

**Comment by elRomano** [comment]
La palette de couleur de material design se présente de cette façon :
![image](https://user-images.githubusercontent.com/25462034/99041847-fb326d80-258b-11eb-94be-4cf605f7b69c.png)

L'idée est que les règles soient les mêmes quelles que soient les teintes choisies. Si mon bouton est de couleur Blue Grey 300 en light mode, alors la couleur de hover sera Blue Grey 800. Et si on est en dark mode ce sera Blue Grey 100. En principe il faudrait utiliser les contrastes de couleur de texte associés à ces teintes mais pour simplifier on considèrera qu'un texte sur une teinte en 800 sera toujours blanche et une teinte en 100 sera toujours noire. Cela simplifiera la mise à jour et dans la mesure où on utilise material design ceux qui reprendront le code ne seront pas déstabilisés par du spécifique.

**Comment by fondation451** [comment]
Done
