### ISSUE TITLE
Change panel background colors and dropshadows

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#352]
## Context
Applying different backgrounds wether we are in a panel or directly in the stage imply several issue concerning button color problems. For instance here the disabled button is more visible than the enabled ones (!!) :
![image](https://user-images.githubusercontent.com/25462034/99282262-c0eaf980-2833-11eb-9ffb-97ff39bba83c.png)
Another argument for this is that in light mode we will have naturally only white background panels so it will make the rules identical on both modes.

## Spec
In order to simplify these things I suggest those 2 things :
- panels and drawer will  have the same color as the screen background (Grey.900 -> #212121).
- to balance the lack of zoning recognition we need to have stronger dropshadows. 
Dropshadow rules : https://www.figma.com/file/yKpu5Hs5bQJr6Ywn5wYWyY/LABEL-Styles?node-id=94%3A16
- Drawers on the left side do not need a drop shadow (it looks ugly when scrolling)

Example :  https://www.figma.com/file/bxeU6RJzyBU1ICL8jrgpva/Maquettes?node-id=69%3A0
![image](https://user-images.githubusercontent.com/25462034/99283376-3c997600-2835-11eb-99df-152dff93ec89.png)
## Drop shadow management
There is a necessity to clarify rules around the use of dropshadows and how they show depending on the dark/light mode.

Link to the css code here : https://www.figma.com/file/yKpu5Hs5bQJr6Ywn5wYWyY/LABEL-Styles?node-id=0%3A1
![image](https://user-images.githubusercontent.com/25462034/99046638-574cc000-2593-11eb-8540-b925e7b01f61.png)

**Comment by fondation451** [comment]
Done
