### ISSUE TITLE
Can't see hover background in the dropdown + border-radius change

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#353]
## Context
![image](https://user-images.githubusercontent.com/25462034/99284029-12948380-2836-11eb-876b-5cd6e77f401a.png)
## Spec
If we follow the same rules as the buttons ([here](https://github.com/Cour-de-cassation/label/issues/332)), hovering should be a grey.100 with a black text.
Dropdown component link : https://www.figma.com/file/bxeU6RJzyBU1ICL8jrgpva/Maquettes?node-id=599%3A12
![image](https://user-images.githubusercontent.com/25462034/99284688-da417500-2836-11eb-9665-3b366bf30ddd.png)

**Comment by fondation451** [comment]
Done
