### ISSUE TITLE
Full category list

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#362]
## Context
By this friday we will need to have the full list of categories in order for the agent to correctly annotate documents
## Spec
Except for the death date (SVG code in comments),Material design Category icons here : https://www.figma.com/file/bxeU6RJzyBU1ICL8jrgpva/Maquettes?node-id=630%3A93
(icon names appear in the inspect tab if you double-click on the icon)
Link to the full category list with associated names, colors, and Material Design colors names for both dark and light mode are here : https://www.figma.com/file/yKpu5Hs5bQJr6Ywn5wYWyY/LABEL-Styles?node-id=120%3A0
![image](https://user-images.githubusercontent.com/25462034/99663746-5a4e2180-2a67-11eb-8468-6940ab377323.png)

**Comment by elRomano** [comment]
```<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M14 4C14 2.89543 13.1046 2 12 2C10.8954 2 10 2.89543 10 4V6H7C5.89543 6 5 6.89543 5 8C5 9.10457 5.89543 10 7 10H10L10 19C10 20.1046 10.8954 21 12 21C13.1046 21 14 20.1046 14 19L14 10H17C18.1046 10 19 9.10457 19 8C19 6.89543 18.1046 6 17 6H14V4Z" fill="white"/>
</svg>
```

**Comment by elRomano** [comment]
@BenoitSerrano Colors and icons are updated (see in specs).

**Comment by elRomano** [comment]
@fondation451 with the change of primary color we need to update the cadastral color to Cyan.600 as the Cyan.800 is now taken for the primary color.

**Comment by fondation451** [comment]
Done
