### ISSUE TITLE
Update primary

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#370]
## Context
Primary color will be the same for both light and dark mode  : cyan.800  (#00838F).
Cadastral category has the same color so it should be changed to cyan.600 in order to keep consistency.

## Information

With black text :

![image](https://user-images.githubusercontent.com/25462034/99663331-b5334900-2a66-11eb-805f-6ad7debaec37.png)

With white text :

![image](https://user-images.githubusercontent.com/25462034/99663357-bfedde00-2a66-11eb-90e2-151abf19550b.png)

**Comment by fondation451** [comment]
Done
