### ISSUE TITLE
Create a category dropdown

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#371]
## Context
Colored dropdowns when you pick a category will help user immediately select the right item.
## Spec
Mockup link : https://www.figma.com/file/bxeU6RJzyBU1ICL8jrgpva/Maquettes?node-id=599%3A12
![image](https://user-images.githubusercontent.com/25462034/99659375-12c49700-2a61-11eb-9436-0c33b3411094.png)

**Comment by fondation451** [comment]
Done
