### ISSUE TITLE
[Feat] Between decision screen

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#394]
## Context
This view shows every time we finish a decision. We need to give a choice on what decision to do next.
## Spec
Screen mockup : https://www.figma.com/file/bxeU6RJzyBU1ICL8jrgpva/Maquettes?node-id=764%3A31
Decision card component : https://www.figma.com/file/bxeU6RJzyBU1ICL8jrgpva/Maquettes?node-id=771%3A59
- We only show icons and amount of categories with more than one entity.
- The number below icons is the number of entities (or it can be the number of annotations)
- If there is more than seven categories we set the number in two rows (as shown in the component screen)
- On hovering icons there is a tooltip showing category name (without the hand cursor as it is not clickable)

Alert form panel : remove the checkbox and the annotation problem option in the dropdown

**Comment by fondation451** [comment]
Done
