### ISSUE TITLE
[Bug] left panel hovered state is slow (sometimes doesn't work)

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#395]
## Description

- Web browser : Firefox
- Branch or commit : master

The rollover state changes with delay when we move the cursor. It gives a feeling of heaviness and sometimes when we stop the mouse on an item it doesn't hover at the right item.

## Screenshot
![image](https://user-images.githubusercontent.com/25462034/99982652-1e8ac300-2dab-11eb-9a45-d753b2b26959.png)

**Comment by fondation451** [comment]
done
