### ISSUE TITLE
[Functional review report] decision view following entity view deletion when resizing

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#443]
## Bug
If I want to resize a entity I have to delete it. But if I am in an entity view and delete the annotation it either disappear (if there are still annonations concerned) or take me back to the top of the global decision view which lose me the focus on what I wanted to resize.
Issue 1 - If we only delete one annotation, it will disappear and yet we will show the same screen so it is really difficult to find the deleted annotation (we would need to quit the detailed view and manually look for the previously deleted term).
Issue 2 - If we delete the whole category we go back to the main decision but it will show at the top so we lose the foucs too.

## Spec propositions
The entity view must be independent to the left panel. A title has to be shown on the top of the right panel so it clearly show what we are looking at, and there is a close button on the top right to close the view. But there is no "locking" in the left so it makes things easier both technically and in terms of UI understanding.
Option for issue 1 - we need to keep the paragraphs shown even if there is no annotation concerned by the detailed view. Doing so will allow other operations to be done without losing the focus.
Option for Issue 2 - we need to keep the view on even if we delete all of the annotations. The left panel can evolve according to the operations but the detailed view is still shown.

**Comment by fondation451** [comment]
done
