### ISSUE TITLE
[Deletion Feature in decision view] "toute la liaison" : Deletion of all the annotations of one linked entity 

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#450]
## Context
In the decision view When we want to delete a group of annotation linked with other annotations (for exemple to resize it) we need to add a feature that deletes the annotations of the same term but not all the linked annotations.
## Spec
In the decision view, only when threre are links in the entity when we click on delete we would have 3 choices :
- "Annotation seule"
- "Annotations identiques"
- "Supprimer tout"

**Comment by fondation451** [comment]
@elRomano @BenoitSerrano 
Pour préciser cette fonctionnalité, on est bien arrêté sur les wordings suivants : 
- "Annotation seule"
- "Annotations identiques"
- "Supprimer tout"

?

De plus, cette extension du dropdown est uniquement pour le bouton dans la tooltip ? Cela ne concerne pas celui du paneau de gauche qui reste un bouton (et pas un dropdown).

**Comment by elRomano** [comment]
Oui tout à fait nous sommes d'accord.
