### ISSUE TITLE
[Functional review report] left panel : "disable" empty categories

### ISSUE THREAD

**Issue by fondation451** [Cour-de-cassation/label#474]
Reviewer: @fondation451 
Date: 07/12/2020
Commit: bbad5e8c83ba67223704abfd347aecc8d9c3e08d
- When a annotation accordeon on the left is empty for a given category, we could give to it a disable color and made it "not clickable"
## Spec propositions
- Remove the dropshadow in the dropdown (for every state please :) )
- Remove the margin for the disabled category so we can see more categories on-screen

![image](https://user-images.githubusercontent.com/25462034/101376894-7a784000-38b1-11eb-8192-773e76138848.png)

**Comment by elRomano** [comment]
We just discussed this topic this morning with Benoit and we totally agree :)

**Comment by elRomano** [comment]
@fondation451 @BenoitSerrano I added mockup proposal

**Comment by elRomano** [comment]
We will decide once we have the final number of categories.

**Comment by elRomano** [comment]
Done.
