### ISSUE TITLE
[Feat] Auto-save

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#508]
## Context
Why not saving any action performed at anytime ?! 
## Spec
- Remove the save draft button
- Record every action performed

**Comment by mauryaland** [comment]
In my opinion, there is no need.  Auto-save will create too much information and complexity. Also, I guess that developments will be more difficult for Benoit and Nicolas.

Saving actions performed when user saves the decision is good enough.

**Comment by elRomano** [comment]
The auto-save could also only save the latest version of the document. There is no need to store all the operations.
But considering the information we had this morning that we need to log operations performed by the users it might be more "needed"... :)

**Comment by fondation451** [comment]
@elRomano @BenoitSerrano 
Est ce toujours d'actualité ?

Avant de le proposer aux utilisateurs, il faudrait en discuter tous ensemble
