### ISSUE TITLE
[Feat] create full treatment object with corresponding annotations

### ISSUE THREAD

**Issue by BenoitSerrano** [Cour-de-cassation/label#538]
## Context
The treatment object only contains basic info (duration, order, _id)
We need to complete it to use it in the admin part

## Spec
- [ ] add treatmentId to assignation
- [ ] add before and after annotations in treatment
- [ ] only display assignated treatments in admin

**Comment by fondation451** [comment]
Ce qu'il reste à faire : 
- refacto commiter (extraction vers le module annotationsDiff)
- réparer la fonction save

**Comment by fondation451** [comment]
New issues have been created for remaining tasks, I close this one.
