### ISSUE TITLE
[Bug] annotation sorting in the "ajouter une liaison" field

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#607]
It is a bit confusing not having the same kind of sorting between the annotation list and the list in the dropdown.
![image](https://user-images.githubusercontent.com/25462034/105721696-25f25800-5f25-11eb-8281-7589cb5f8ab2.png)

## Spec propositions
- We should use the same rules of sorting (taking the number of annotations into account) between both lists.

**Comment by fondation451** [comment]
Done
