### ISSUE TITLE
[Bug] Cannot annotate some words

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#612]
## Description
Sometimes when we create an annotation we can do all the process but the annotation does not appear.
Spotted on : 
- Decision 1295019 : "consorts Durand-Dupond" Impossible to separate Raoux and Celso.
- Decision 1295004 : "Aljab Building ,  Rig Road, Doha (Qatar)". Impossible to annotate correctly

**Comment by BenoitSerrano** [comment]
The cause of the bug with ""Aljab Building , Rig Road, Doha (Qatar)". Impossible to annotate correctly" is an non-detection in the annotationTextDetector file - no indexOf returns a valid value.
My hypothesis: the Selection.toString()  object in DocumentText.tsx formats the string, and there appears to be a strange space between Building and Rig.
In this case, two possibilities : 
- format the initial text to replace strange spaces with actual ones
- do not use Selection.toString(), but calculate it with the index,  the string length and the document text

**Comment by fondation451** [comment]
@BenoitSerrano 
Je regarde

**Comment by fondation451** [comment]
Done
