### ISSUE TITLE
[Functional review report : annotation deletion] missing possibility to delete a representant

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#613]
So far when we select an annotation in the document panel that has linked representants, we can either delete the whole entity or only the single annotation. We miss the possibility to delete all the annotations of the same representant without deleting linked representants.

This would be called "Effacer le représentant (6 annot.).

Screenshot sent by email (look for issue #613 in your mailbox).

**Comment by fondation451** [comment]
@elRomano C'est doublon de https://github.com/Cour-de-cassation/label/issues/675, non. On peut fermer ?
