### ISSUE TITLE
[Bug @bkpanonym : document selector ] Date format is wrong

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#632]
## Description
On the staging server the date format is not correct.
## What it is currently :
![image](https://user-images.githubusercontent.com/25462034/106252030-0c4b5c00-6216-11eb-884d-da9c2dbfff6f.png)
## How it should be :
![image](https://user-images.githubusercontent.com/25462034/106252273-5d5b5000-6216-11eb-9835-8eb9cf82eb06.png)

## Sidenote
This is what was expected as the final design :)
![image](https://user-images.githubusercontent.com/25462034/106252763-e4102d00-6216-11eb-860b-12188f1f20f4.png)

**Comment by fondation451** [comment]
Le bug n'est pas reproductible en local. Il faudra le traiter à la cour.
