### ISSUE TITLE
[Bug : documentSelector] wrong count of linked entities

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#641]
## Description
Link counting is different between the resume in the decision selector and the actual links number.
We can consider a link as when two representant are bound together (or one arch = one link)

In the following decision we count 3 links instead of 7.

## Spec
A "liaison" is considered as one when two representant are linked together

## Screenshot
![image](https://user-images.githubusercontent.com/25462034/106461807-8fc6b080-6495-11eb-8742-2971c7fc26e9.png)
![image](https://user-images.githubusercontent.com/25462034/106462301-2e531180-6496-11eb-8a36-4dd7ba8e974f.png)

**Comment by fondation451** [comment]
Done
