### ISSUE TITLE
[Feat] category list update

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#648]
## Context
Wen need to add new categories in the list. Some colors and namings from previous categories had to be changed to fit the needs.

## New icons
https://www.figma.com/file/bxeU6RJzyBU1ICL8jrgpva/Maquettes?node-id=1560%3A15

## New colors (physico-morale and Telephone/fax changed too) 
![image](https://user-images.githubusercontent.com/25462034/106594698-c1ea1800-6552-11eb-82ea-5ec09304ca9d.png)

**Comment by fondation451** [comment]
@BenoitSerrano 
C'est fait, n'est ce pas ? Je ferme

**Comment by elRomano** [comment]
Icons are not updated.

**Comment by elRomano** [comment]
- locality -> location_city
 - birth date -> cake
 - email -> email
 - custom -> edit

**Comment by BenoitSerrano** [comment]
@elRomano peux-tu tester maintenant et me dire si tout est ok ?

**Comment by fondation451** [comment]
@elRomano C'est bon, on peut fermer ?

**Comment by elRomano** [comment]
Oui c'est bon !
