### ISSUE TITLE
[Bug] corrupted special character in annotations

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#657]
## Description
When there are special characters in annotations they are corrupted. Deleting the annotation and recreating does not show the problem.

## Screenshot
![image](https://user-images.githubusercontent.com/25462034/106908925-0b2b9a80-6700-11eb-807f-60fb491e7b0d.png)

**Comment by fondation451** [comment]
Ce n'est pas un bug en prod.
Cela est du à l'encodage de nos données de tests en local.

**Comment by fondation451** [comment]
Done
