### ISSUE TITLE
[Bug] Annotation index calculation

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#658]
## Description
When changing annotations in a decision the indexes are not recalculated so it can end up validating decision with [address 5] though there is only one adress indexed.

## Screenshot
<img width="1629" alt="Capture d’écran 2021-02-04 à 16 26 34" src="https://user-images.githubusercontent.com/25462034/106916695-c146b280-6707-11eb-9053-720351d07348.png">

**Comment by fondation451** [comment]
Done
