### ISSUE TITLE
[Bug] doublons d'entité

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#660]
## Description 1
- Je supprime une entité de plusieurs mots, 
- Je recrée une nouvelle entité plus courte
- J'en crée une autre juste à son côté (droite ou gauche)
-  je rafraichis
 
Alors la première des deux entités créée est affichée en doublon.

## Description 2
- J'ouvre une décision
- Je crée une annotation (sur un terme non annoté précédemment)
- Je crée une autre annotation
- Je rafraichis

Alors la première entité s'affiche en doublon

**Comment by fondation451** [comment]
Done
