### ISSUE TITLE
[Bug] Annotation with a deprecated category

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#666]
## Description
A category not supposed to be shown is activated but not visible which prevent annotating with a real category.

## Screenshot
https://drive.google.com/file/d/1wSh_j32efWaQqIbvd_d3Z3meex4FaDE9/view?usp=sharing

## Spec :
- change category icon to sens interdit
- change category color to grey

**Comment by mauryaland** [comment]
Fixed in Cour-de-cassation/nlp-pseudonymisation-api#5
