### ISSUE TITLE
[Feature in admin profile] having footer in the decision view + back button

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#674]
## Description
There is no "Validate" button in the admin view of a document.
There are two main scenarios for the admin in the treatments table : 
- the admin opens the decision, see that there is nothing to add nor to remove, and click on the Back button to go back to the treatments
- [ ] No empty treatment should be visible in the treatments table

- the admin opens the decision, corrects some mistakes, and then click on Back button to go back to the treatments
- [ ] A new treatment created by the administrator is now in the table, unless it is empty

**Comment by BenoitSerrano** [comment]
@elRomano Pas de footer dans la vue admin, car on a dit que l'admin ne pouvait pas encore faire de modif. On n'a encore rien décidé concernant cette feature. Mais on peut ouvrir la discussion :)

**Comment by elRomano** [comment]
Je ne me souvenais pas que l'on s'était dit ça mais c'est "Claire"ment un besoin :)

**Comment by fondation451** [comment]
To clarify the spec.

## Spec
- The modifications are saved with an auto save
- The autosave create a treatment if no treatments exists
- The back button should check that the treatment is not empty. If it is empty, it should delete it.
