### ISSUE TITLE
[Feature] replacement term for dates

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#682]
## Description
Date replacement must be [XX/XX/year] with the correct year visible.

**Comment by elRomano** [comment]
We need to decide what to do when the year in not detected

**Comment by mauryaland** [comment]
As discussed on last monday, the task of isolated the year in a date could be achieved on the juritools side. Could you confirm it @UrszulaCzerwinska, @BenoitSerrano, @fondation451, @elRomano ?

**Comment by fondation451** [comment]
@mauryaland 
It would be better to do it in juritools, I agree.

But there is still a hole in the spec. What do we do when there are no year in the date ? This should be discussed next monday.

**Comment by BenoitSerrano** [comment]
@elRomano @fondation451 do we close this issue?

**Comment by elRomano** [comment]
@fondation451 @BenoitSerrano Date has to be [date + index], index being an incremental number.

**Comment by elRomano** [comment]
Examples :
[date naissance 1]
[date décès 4]
[date mariage 2]
