### ISSUE TITLE
[Functional review] Annotation Creation with "appliquer à tous" should be case insensitive

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#697]
This is a clear demand from Claire.

## Spec
When a user creates a new entity the same annotation detection must detect every same terms withtout taking care of the case used. Therefore, if I select "Dupond" and create a new entity, "DUPOND" must automatically be included in the entity creation.

## On the left panel
OPTION 1 :
We keep the link between the two and show both representants
OPTION 2 :
We show only one version and consider them as one representant. Therefore one representant can embed both uppercase and lower case terms as long as they have the same characters.

**Comment by fondation451** [comment]
@elRomano 
> When a user creates a new **category** the same annotation detection must detect every same terms withtout taking care of the case used. Therefore, if I select "Dupond" and create a new entity, "DUPOND" must automatically be included in the entity creation.

A new annotation ?

**Comment by elRomano** [comment]
Yes it is.
