### ISSUE TITLE
[Functional review report] Showing logged account

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#769]
Claire's is telling us that it is annoying having no way to know who is connected.

## Proposition
- We could show the login in the settings panel (we could integrate also the logout button as it is almost never used) so it doesn't overload the general layout.

![image](https://user-images.githubusercontent.com/25462034/110130994-f78c5600-7dc9-11eb-8519-e055343126ad.png)

**Comment by fondation451** [comment]
Done
