### ISSUE TITLE
[Feat] Prevent multiple calls to the route /documents-to-be-treated

### ISSUE THREAD

**Issue by BenoitSerrano** [Cour-de-cassation/label#771]
## Context
A malicious agent or a hacker can fetch the whole content of the LABEL database by hitting the /documents-to-be-treated endlessly. We need to prevent that behaviour

## Spec
- prevent the route /documents-to-be-treated to be called more than 3 times a minute

**Comment by fondation451** [comment]
duplicate https://github.com/Cour-de-cassation/label/issues/865
