### ISSUE TITLE
[Feat] agents page

### ISSUE THREAD

**Issue by BenoitSerrano** [Cour-de-cassation/label#779]
## Context
The administrator wants a view to handle his/her agents, their personal statistics, and so on

## Spec

DISPLAY
- [x] name
- [x] role
- [x] email
- [ ] statistics

FEATURES
- [ ] possibility to delete an agent
- [x] possibility to register an agent
- [ ] possibility to modify an agent
- [x] possibility to reset its password

**Comment by elRomano** [comment]
Redundant with https://github.com/Cour-de-cassation/label/issues/966
