### ISSUE TITLE
[Feat] track publication type in administration

### ISSUE THREAD

**Issue by BenoitSerrano** [Cour-de-cassation/label#823]
## Context
We want to track (so we can treat faster) some documents that are published according to a certain "publication type" (P, B, R, I, etc.)
We first need to extract it from the SDER database, then store it in LABEL's, then display it in the admin table

## Spec
- [ ] fetch  `zoning.introduction_subzonage.publication` when importing the documents
- [ ] add a `publicationCategory` field in the document "document", that is an array of string
- [ ] in the untreated document table, display the corresponding letter(s) in the column
- [ ] add a filter that makes possible to only display "P" decisions

**Comment by fondation451** [comment]
Pourquoi pas seulement `category` ? C'est plus générique ?

**Comment by BenoitSerrano** [comment]
> Pourquoi pas seulement `category` ? C'est plus générique ?

Il semblerait que ce soit une erreur métier de parler de catégorie de décision, et que ça catégorise la catégorie de la publication
