### ISSUE TITLE
[Feat] Allow the admin to annotate like an annotator

### ISSUE THREAD

**Issue by fondation451** [Cour-de-cassation/label#862]
## Context

Après une discussion avec Claire, il semble important de donner la possibilité à un administrateur de pouvoir annoter des décisions comme un annotateur.

Le cas d'usage est le suivant : une partie de l'équipe d'annotateur est malade ou en congé. L'administrateur doit pouvoir prêter main forte pour pouvoir garantir un traitement minimal.

**Comment by elRomano** [comment]
Oui c'est important qu'un administrateur puisse annoter des décision
