### ISSUE TITLE
[Functional review report] Statistics computation

### ISSUE THREAD

**Issue by elRomano** [Cour-de-cassation/label#874]
## Context
We need to count in statistics annotations that has both a resize and a category change.

## Spec propositions

- [x] Change "Mod." column name  to "Cat."
- [x] If terms in a new annotation is found in the older one but without the same size then there is a R+ or R-, no matter the category change
- [x] If terms in a new annotation have a different category than the older one then there is a category change, no matter the size change (or not)

**Comment by fondation451** [comment]
Exemple : 
{ "Jeff", "prénom"} transformé en { "Jeff de Bruges", "morale"}, cela va compter dans deux compteurs : à la fois R+ et à la fois Cat (changement de catégorie).

**Comment by elRomano** [comment]
Tested and OK
