### ISSUE TITLE
[Feat] add decision number search in filters

### ISSUE THREAD

**Issue by BenoitSerrano** [Cour-de-cassation/label#915]
## Context
The administrator wants to access specific decision by typing the number

## Spec
![image](https://user-images.githubusercontent.com/28384444/113714559-cf558700-96e8-11eb-8760-6bf8f0dbeae6.png)

**Comment by elRomano** [comment]
@BenoitSerrano it is functionnally ok but :
- The font is not the right one
- You should still add a zoom icon so we know we're in search mode when we type something (a drawing is worth a thousand words)
- We need to add it to the decision stream as I think it will be useful too (and it might have even more decisions)
