### ISSUE TITLE
[Feat] Add decision id in the decision page

### ISSUE THREAD

**Issue by mauryaland** [Cour-de-cassation/label#956]
## Context

For debugging purposes, we need a fast access to the decision id to easily get to the raw document. It is valuable to have it in the front page of the decision when Claire or a non-technical person report a problem.

## Spec

Put the document id in the label decision page, it could be added in the title of the decision or somewhere else

**Comment by elRomano** [comment]
We should rather add a "registerNumber" column in the admin page as this id is internal and agents do not need to have two ids shown. It will keep the decision view clean. Research will be available for both numbers.

**Comment by mauryaland** [comment]
As soon as we can access the information, it is fine for me. Could you create an admin account for @UrszulaCzerwinska and I ?

**Comment by UrszulaCzerwinska** [comment]
How will know then, when receiving bug report from an agent which decision is concerned?

**Comment by elRomano** [comment]
You can find the decision (and optionnally open it) in the admin page with the search field.

You already have an account for both preprod and production. I'll send you the password for the production server through whatsapp

**Comment by UrszulaCzerwinska** [comment]
But what will be the search term if the agent doesn't know the id?

**Comment by elRomano** [comment]
Ideally he will send an alert so you will have a direct access to the decision, but he will give Claire the registerNumber value.
Having two numbers for the agent to give is too complicated. So the agents use the "official" reference and we use the technical one if needed. The admin page is here to make the link.

**Comment by UrszulaCzerwinska** [comment]
What is official reference then?

**Comment by elRomano** [comment]
By official I mean the one used by magistrates and others. It is registerNumber in the SDER database.

**Comment by UrszulaCzerwinska** [comment]
Which is this number? I don't know about any universal id used by "magistrate and others". 
The thing is that every time someone has a request, we are send snapshots or parts of text and we are not able to identify it in the database. The numbers like nr RG are not unique (I cannot find a unique decision with the number). For Jurinet , I don't know about any number that allow us to find the decision in the database. 

What about about adding the decision id in the interface till we have easy acess to the sder database or the admin interface? That would make debuging way faster for everyone.

If we can get any number that allows us to find the decision in the database, I will be fine with it.

**Comment by elRomano** [comment]
OK. My concern is that we will use technical ids for non technical matter, and such id might circulate in groups (I think in particular for publishing and occultation reclamation) that will not understand where this number comes from. But we can discuss this in the next meeting.

**Comment by elRomano** [comment]
Done.
