### ISSUE TITLE
[Feat] Remember the filters or sorting in admin "Décisons traités" tab

### ISSUE THREAD

**Issue by UrszulaCzerwinska** [Cour-de-cassation/label#977]
## Context
When I am in admin Label, I am in tab "Décisons traités" I go to the page 3 and I open the décision, then I go back => I get to page 1 instead of 3 
Therefore if I want to open one by one all décisions from page 3 of listing, I need to from page 1 to 3 every time

Similarly, I apply a sort by agent name, I open first top of the decisions then I go back I need to redo the sort.

## Spec
Make listing remember the place from where I opened the decision and get me back there.

**Comment by elRomano** [comment]
Tested and ok
